libutils: Fix missing definition of shared_ptr and unique_ptr
This includes memory header for shared_ptr and unique_ptr templates.
Fixes the following errors:

RefBase.h:803:1: error: ‘shared_ptr’ does not name a type
RefBase.h:810:1: error: ‘unique_ptr’ does not name a type

Change-Id: I6a7a67333c9ef05250c5a3c6199d7fac288f946b

Former-commit-id: bc7788310f5fc93149c1b3c6b8d5934de1f9b6cf
Former-commit-id: 8d1cf0032f04113e8c890ed29013ed26446e69b0